### ISSUE TITLE
Importing .wasm file in front-end

### ISSUE THREAD

**Issue by msinkec** [sCrypt-Inc/zk-battleship#8]
On the zokrates branch (master), when I try to use the package `zokrates-js@1.1.4` upon building it fails with messages like these:

```
ERROR in ./node_modules/zokrates-js/pkg/index.js 3:0-21
Can't import the named export '__wbindgen_start' (imported as 'wasm') from default-exporting module (only default export is available)

ERROR in ./node_modules/zokrates-js/pkg/index_bg.js 11:40-58
Can't import the named export 'memory'.'buffer' (imported as 'wasm') from default-exporting module (only default export is available)

ERROR in ./node_modules/zokrates-js/pkg/index_bg.js 76:40-58
Can't import the named export 'memory'.'buffer' (imported as 'wasm') from default-exporting module (only default export is available)

ERROR in ./node_modules/zokrates-js/pkg/index_bg.js 109:19-55
Can't import the named export '__wbindgen_add_to_stack_pointer' (imported as 'wasm') from default-exporting module (only default export is available)

ERROR in ./node_modules/zokrates-js/pkg/index_bg.js 110:4-16
Can't import the named export 'compile' (imported as 'wasm') from default-exporting module (only default export is available)

ERROR in ./node_modules/zokrates-js/pkg/index_bg.js 119:4-40
Can't import the named export '__wbindgen_add_to_stack_pointer' (imported as 'wasm') from default-exporting module (only default export is available)
```

As far as I understand this happens because inside the `zokrates-js` package there is the following import statement:
```ts
import * as wasm from './index_bg.wasm';
```

This import statement is not standard and needs some additional configuration for webpack. I already added the config overrides file for webpack from the older version of the app (where it seemed to work?) to no avail.

`zokrates-js@1.1.5` is working because the wasm there is inline, encoded in base64, but we can't use that version because the proofs from our ZoKrates fork are incompatible.

**Comment by zhfnjust** [comment]
the webpack config used before: https://github.com/sCrypt-Inc/battleship-zkSNARK/blob/5fd5aeaff6ca5998c0bd1b39085445fef0e5e725/config-overrides.js#L1

does it work for you ?

**Comment by msinkec** [comment]
This is where I took the wasm rules initially from. It's the same in master branch now. Doesn't work though.
